[[collection]]
type = "card"
title = "embcli"
content = "Command-line utility tool for embeddings"
tags = ["python", "cli", "nlp"]
link = "https://embcli.mocobeta.dev/"

[[collection]]
type = "card"
title = "Janome"
content = "Japanese tokenizer library written entirely in Python"
tags = ["python", "nlp"]
link = "https://janome.mocobeta.dev/"

[[collection]]
type = "card"
title = "Apache Lucene (committer)"
content = "Search library written entirely in Java"
tags = ["java", "search"]
link = "https://github.com/apache/lucene"

[[collection]]
type = "card"
title = "[archived] Luke (co-maintainer)"
content = "GUI tool for introspecting Lucene index"
tags = ["java", "search"]
link = "https://github.com/DmitryKey/luke"

[[collection]]
type = "card"
title = "検索システム ― 実務者のための開発改善ガイドブック (共著)"
content = "「情報検索」×「データサイエンス」×「全文検索エンジン」"
date = "2022年5月第1版発行"
tags = ["book", "search"]
link = "https://www.lambdanote.com/products/ir-system"

[[collection]]
type = "card"
title = "n月刊ラムダノート Vol.3, No.1 (寄稿)"
content = ""
date = "2021年8月発行"
tags = ["magazine"]
link = "https://www.lambdanote.com/collections/n/products/nmonthly-vol-3-no-1-2021"

[[collection]]
type = "card"
title = "改定第3版 Apache Solr入門 (共著)"
content = ""
date = "2017年4月発行"
tags = ["book", "search"]
link = "https://gihyo.jp/book/2017/978-4-7741-8930-7"

